name: Build and Publish Dev Container

on:
  push:
    branches: [main, dev]
    paths:
      - ".devcontainer/**"
      - "Dockerfile*"
      - ".github/workflows/build-devcontainer.yml"
  pull_request:
    branches: [main, dev]
    paths:
      - ".devcontainer/**"
      - "Dockerfile*"
      - ".github/workflows/build-devcontainer.yml"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  # Lint code and Dockerfile before building
  lint:
    name: Lint Code and Dockerfile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Super-Linter
        uses: super-linter/super-linter@v7
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_DOCKERFILE_HADOLINT: true
          VALIDATE_BASH: true
          VALIDATE_YAML: true
          VALIDATE_JSON: true
          VALIDATE_MARKDOWN: true
          FILTER_REGEX_INCLUDE: .*

  # Build and push container image
  build:
    name: Build Container
    runs-on: ubuntu-latest
    needs: lint
    permissions: write-all

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3


      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,prefix={{branch}}-
          labels: |
            org.opencontainers.image.title=Modern Development Container
            org.opencontainers.image.description=A modern development container with Debian 12, Oh My Zsh, Mise, and Starship
            org.opencontainers.image.vendor=smerlos
            org.opencontainers.image.licenses=MIT

      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: .devcontainer/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
