name: Quality Checks

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    name: Super Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Super Linter
        uses: github/super-linter@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_WORKING_DIRECTORY: .
          VALIDATE_DOCKERFILE_HADOLINT: true
          VALIDATE_SHELL_SH: true
          VALIDATE_MARKDOWN: true
          VALIDATE_JSON: false
          VALIDATE_YAML: false

  container-scan:
    name: Container Security Scan
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Build Docker image
        run: docker build -t dev-container:latest .
      - name: Run Trivy vulnerability scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: dev-container:latest
          format: table
          exit-code: '1'
          vuln-type: 'os,library'
          severity: 'HIGH,CRITICAL'
