name: Build Backend Container

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  filter:
    runs-on: ubuntu-latest
    outputs:
      backend_changed: ${{ steps.filter.outputs.backend }}
    steps:
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            backend:
              - apps/backend/**

  lint:
    needs: filter
    if: ${{ needs.filter.outputs.backend_changed == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Super Linter
        uses: super-linter/super-linter@v7
        env:
          GITHUB_TOKEN: ${{ github.token }}

  build:
    needs: lint
    if: ${{ needs.filter.outputs.backend_changed == 'true' }}
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/backend
          tags: |
            type=sha,prefix={{branch}}-
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: apps/backend/ci/Dockerfile
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
